<a href="https://colab.research.google.com/github/mariavirna/Fun-es/blob/main/Fun%C3%A7%C3%B5es_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 1) Crie uma função chamada calcula_imc(peso=70, altura=1.75) que retorne o valor do IMC. (Fórmula: peso / altura²).
def calcula_imc(peso=70, altura=1.75):
  return peso / (altura ** 2)
calcula_imc()

22.857142857142858

In [7]:
# 2) Dado uma lista chamada alturas com os seguintes elementos:
alturas = [45, 23, 67, 12, 11, 89, 23, 41, 50, 62, 78, 34, 56, 19, 72, 88, 11,
           90, 39, 65, 76, 27, 48, 59, 81, 14, 11, 93, 3, 68, 29, 52, 74, 16,
           85, 20, 55, 38, 69, 11, 83, 7, 44, 61, 18, 96, 22, 58, 31, 71, 40,
           53, 87, 31]
print(alturas)

[45, 23, 67, 12, 11, 89, 23, 41, 50, 62, 78, 34, 56, 19, 72, 88, 11, 90, 39, 65, 76, 27, 48, 59, 81, 14, 11, 93, 3, 68, 29, 52, 74, 16, 85, 20, 55, 38, 69, 11, 83, 7, 44, 61, 18, 96, 22, 58, 31, 71, 40, 53, 87, 31]


In [9]:
# Utilize as funções padrão do Python para calcular e exibir:
# O maior valor do conjunto de dados
print("Maior valor:", max(alturas))

# O menor valor do conjunto de dados;
print("Menor valor:", min(alturas))

# A soma de todos os valores;
print("Soma dos valores:", sum(alturas))

# O valor absoluto de um número negativo (-25);
print("Valor absoluto de -25:", abs(-25))

# O arredondamento do número 3.14159 para 2 casas decimais.
print("Arredondamento de 3.14159:", round(3.14159, 2))

Maior valor: 96
Menor valor: 3
Soma dos valores: 2606
Valor absoluto de -25: 25
Arredondamento de 3.14159: 3.14


In [11]:
# Utilize as funções do módulo statistics para calcular e exibir:
from statistics import *

# A média dos dados
print("Média:", mean(alturas))

# A mediana dos dados
print("Mediana:", median(alturas))

# A moda dos dados
print("Moda:", mode(alturas))

# A variância da amostra dos dados
print("Variância:", variance(alturas))

# O desvio padrão da amostra dos dados
print("Desvio padrão:", stdev(alturas))

Média: 48.25925925925926
Mediana: 49.0
Moda: 11
Variância: 741.1013277428372
Desvio padrão: 27.223176297831913


In [12]:
# 3) Crie duas matrizes aleatórias:
# Uma matriz 5x10 de números float aleatórios entre 0 e 1.
from numpy import *
a = random.random((5, 10))
print(type(a))
print(a)

# Uma matriz 8x4 de números inteiros aleatórios entre 0 e 9.
b = random.randint(10, size=(8, 4))
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[0.14786896 0.20455148 0.16417282 0.19349107 0.8151545  0.5264438
  0.58879506 0.8741794  0.24213852 0.85546648]
 [0.17513627 0.06402572 0.94011229 0.10899267 0.55701096 0.01007043
  0.51814896 0.69288674 0.26812276 0.25383344]
 [0.13996613 0.15077173 0.78554683 0.84960311 0.65378837 0.78546376
  0.05001504 0.90281379 0.53516093 0.88557902]
 [0.1929836  0.69121844 0.77658144 0.69452798 0.74581368 0.40596892
  0.9813533  0.10218463 0.50104933 0.60841192]
 [0.56876436 0.890918   0.37843296 0.1641459  0.64357198 0.81612694
  0.64402162 0.3898135  0.06667776 0.87978044]]
<class 'numpy.ndarray'>
[[2 5 4 0]
 [5 6 5 9]
 [6 0 2 0]
 [9 5 0 2]
 [4 9 9 2]
 [9 3 4 8]
 [5 5 4 6]
 [0 6 7 5]]
